kind: Secret
apiVersion: v1
metadata:
  name: {{ include "k8s-wordpress.fullname" . }}-backup
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws_access_key_id | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws_secret_access_key | b64enc }}
type: Opaque
